"use client";

import React from "react";
import { HeirResult, EstateDetails } from "@/lib/types";

interface PrintableReportProps {
  deceased: EstateDetails;
  results: HeirResult[];
}

export function PrintableReport({ deceased, results }: PrintableReportProps) {
  return (
    <div className="print-only p-8 bg-white text-black font-sans max-w-4xl mx-auto">
      <div className="border-b-2 border-primary pb-4 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold text-primary">WarithGuide</h1>
          <p className="text-sm text-gray-500 italic">Inheritance Summary Report</p>
        </div>
        <p className="text-sm">{new Date().toLocaleDateString()}</p>
      </div>

      <div className="mb-10 bg-gray-50 p-6 rounded-lg">
        <h2 className="text-xl font-semibold mb-4 border-b pb-2">Estate Information</h2>
        <div className="grid grid-cols-2 gap-y-3">
          <p><span className="font-semibold">Deceased:</span> {deceased.deceasedName}</p>
          <p><span className="font-semibold">Total Estate Value:</span> {new Intl.NumberFormat('en-US', { style: 'currency', currency: deceased.currency || 'USD' }).format(deceased.estateValue)}</p>
          {deceased.notes && <p className="col-span-2"><span className="font-semibold">Notes:</span> {deceased.notes}</p>}
        </div>
      </div>

      <div className="mb-10">
        <h2 className="text-xl font-semibold mb-4 border-b pb-2">Distribution Breakdown</h2>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-gray-100">
              <th className="p-3 border">Beneficiary</th>
              <th className="p-3 border">Type</th>
              <th className="p-3 border">Share Fraction</th>
              <th className="p-3 border">Percentage</th>
              <th className="p-3 border text-right">Monetary Value</th>
            </tr>
          </thead>
          <tbody>
            {results.map((heir, idx) => (
              <tr key={idx} className={idx % 2 === 0 ? "bg-white" : "bg-gray-50"}>
                <td className="p-3 border font-medium">{heir.relationship}</td>
                <td className="p-3 border">{heir.heirType}</td>
                <td className="p-3 border">{heir.fraction}</td>
                <td className="p-3 border">{heir.percentage.toFixed(2)}%</td>
                <td className="p-3 border text-right font-bold">
                   {new Intl.NumberFormat('en-US', { style: 'currency', currency: deceased.currency || 'USD' }).format(heir.amount)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-12 pt-8 border-t text-xs text-gray-400 text-center">
        <p>This report was generated by WarithGuide. Calculations are based on general Sunni Islamic inheritance principles (Fara'id).</p>
        <p>For complex cases, please consult with a qualified Islamic legal scholar or professional advisor.</p>
      </div>
    </div>
  );
}